version: 1.2.0.{build}
os: Visual Studio 2015 RC
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-{branch}'
environment:
  Configuration: Release
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
nuget:
  project_feed: true
before_build:
- nuget restore
build:
  verbosity: minimal
artifacts:
- path: 'src\**\*.nupkg'
  name: poshgit2
