version: 1.2.0.{build}
os: Visual Studio 2015 RC
environment:
  Configuration: Release
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- choco install gitversion.portable -pre -y
assembly_info:
  patch: false
nuget:
  disable_publish_on_pr: true
  project_feed: true
before_build:
- nuget restore
- ps: gitversion /l console /output buildserver /updateAssemblyInfo
build:
  verbosity: minimal
artifacts:
- path: 'src\**\*.nupkg'
  name: poshgit2
deploy:
- provider: NuGet
  server: https://www.myget.org/F/poshgit2/api/v2
  api_key:
    secure: g4eIWfNzoYNyrki3K4swxrlu8g8QDF6RSyUJbPAVO4Gj4BPYicfPPweryugIUE3C
  symbol_server: https://nuget.symbolsource.org/MyGet/poshgit2
  artifact: poshgit2
  on:
    branch: master
